---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-added-large-files

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  - repo: local
    hooks:
      - id: make-lint
        name: make lint
        entry: make lint
        language: system
        files: \.(yml|yaml)$
        pass_filenames: false

      - id: lint-apps
        name: lint apps
        entry: make lint-apps
        language: system
        files: ^apps/.*/values.*\.yml$
        pass_filenames: false
